# Generated by Django 3.0.3 on 2020-02-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='product', max_length=150),
            preserve_default=False,
        ),
    ]
