# Generated by Django 3.0.3 on 2020-03-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availabily',
            field=models.CharField(blank=True, choices=[('S', 'In Stock'), ('0', 'Out Of Range')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DR', 'Drink ware'), ('YG', 'Yoga Store'), ('CA', 'Clothing & Accessories')], default='yoga items', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='na', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
